# Programming 1 – Calculations in Python

Authors:
- Dr Tom Slater

Email: slatert2@cardiff.ac.uk

## Learning Objectives
-	Use Jupyter notebooks to execute Python code.
-	Define and call functions, including single-line functions using lambda.
-	Use Python functions to calculate basic thermodynamic quantities.

## Table of Contents

1. [Variables and Types](#variables)       
2. [Mathematical Operations](#maths)
3. [NumPy](#numpy)
4. [Functions](#functions)
5. [Lambda Functions](#lambda)
6. [End of Session Task](#final-task)

### Further reading for this topic

- [Software carpentry lessons](http://swcarpentry.github.io/python-novice-gapminder/index.html)

**<span style="color:black">Jupyter Cheat Sheet</span>**
- To run the currently highlighted cell and move focus to the next cell, hold <kbd>&#x21E7; Shift</kbd> and press <kbd>&#x23ce; Enter</kbd>;
- To run the currently highlighted cell and keep focus in the same cell, hold <kbd>&#x21E7; Ctrl</kbd> and press <kbd>&#x23ce; Enter</kbd>;
- To get help for a specific function, place the cursor within the function's brackets, hold <kbd>&#x21E7; Shift</kbd>, and press <kbd>&#x21E5; Tab</kbd>;

## 1. Variables and Types
<a id='variables'></a>

Python variables store data. Variables can have almost any name but it's best to use an understandable name. For example:

In [ ]:
mass_of_electron = 9.1093837e-31

The most used style guide for programming in Python is [PEP8](https://peps.python.org/pep-0008/). This style guide notes that variables should include only lowercase letters and words should be separated by underscores. Hence the name used above!

Variables can have a variety of different types. To determine the type of a variable, we can apply the type() function to the variable.

In [ ]:
type(mass_of_electron)

float

The most common types (most of which we saw in first year programming) include:

- Integers (int): Whole numbers.
- Floating point numbers (float): Any real number including a decimal point.
- Strings (str): Groups of characters, e.g. a word or sentence.
- Booleans (bool): True or false.
- Lists (list): Collection of multiple items.

As examples:

In [ ]:
quantum_number = 2
print(type(quantum_number))

mass_of_electron = 9.1093837e-31
print(type(mass_of_electron))

scientist_name = "Erwin Schrödinger"
print(type(scientist_name))

cat_alive = True
print(type(cat_alive))

first_five_numbers = [1, 2, 3, 4, 5]
print(type(first_five_numbers))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'list'>


One of the big benefits of Python is that you don't have to declare the type of a variable, Python interprets the type for you. You can also change the type of a variable, which can be useful but can also present risks!

In [ ]:
mass_of_electron = 1
print(type(mass_of_electron))

<class 'int'>


<div class="alert alert-success">
<b>Task 1.1: Define and assign variables with suitable names for:<br></b>
- The ideal gas constant.<br>
- The atomic number of an element (pick your favourite).<br>
- The name of an element (pick your favourite).

</div>    

In [ ]:
#Enter code for Task 1.1 here
r = 3.814
element = 1
element_name = 'H'

<div class="alert alert-success">
<b>Task 1.2: Create a list that contains all of the variables created in Task 1.1.<br></b>

Note here: Lists can contain items of different types!

</div>    

In [ ]:
#Enter code for Task 1.2 here
var = [r, element, element_name]

## 2. Simple mathematical operations
<a id='maths'></a>

In this session, we will be using Python to perform mathematical operations. Python has a number of native mathematical operators, which include:

- (+) : addition
- (-) : subtraction
- (/) : division
- (//): floor division
- (*) : multiplication
- (**): raise to the power

These are mostly straightforward, as shown in the examples below:

Addition:

In [ ]:
3+2

5

Multiplication:

In [ ]:
3*2

6

Exponentials:

In [ ]:
3**2

9

The two division operators require a little more explanation. The (/) operator does division in a standard way, i.e. it will output a non-integer if the numerator is not divisble by the denominator.

In [ ]:
3/2

1.5

However, the (//) operator will do the division and round down to the nearest integer.

In [ ]:
3//2

1

This is true even if using floating point numbers!

In [ ]:
3.0//2.0

1.0

### 2.1 Mathematical operations on lists

Some of the operators above also work on lists, but in a manner that is very different to their operations on integers or floating point numbers.

For instance, the + operator concatenates (joins together) the two lists here, rather than adding the values together.

In [ ]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

It's possible to multiply a list by an integer, but this simply adds copies of the list elements to the list.

In [ ]:
[1, 2] * 2

[1, 2, 1, 2]

For many calculations, we will have a one-dimensional set of data that we would like to perform a mathematical operation on. We've seen that this is difficult to achieve with lists, but next we'll move onto the NumPy package which makes this much easier.

<div class="alert alert-success">
<b>Task 2.1: Perform the following calculations:<br></b>
- Add 3.14 to 2.72.<br>
- Set the variable `a` to be 3. Multiply `a` by 4.<br>
- Set the variable `b` to be 1. Add 3 to `b` and then raise it to the power 3.

</div>

In [ ]:
#Enter code for Task 2.1 here
3.14 + 2.72
a = 3
a *= 4
print(a)
b = 1
b += 1
b = b**3
print(b)

12
8


## 3. NumPy
<a id='numpy'></a>

NumPy is the standard package for working with numerical arrays in Python. We can import NumPy using the `import` statement. Here, we are importing NumPy to use with the name `np`.

In [ ]:
import numpy as np

An array is similar to a matrix, but can have any number of dimensions. We'll stick to one dimension in this session.

To create an array, you can use the `array` function within NumPy with a list of numbers as input.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


To create larger arrays, there are other in-built functions. For example, to create a linearly-spaced array (i.e. the same interval between all elements), the `linspace` function can be used. Using `linspace` requires arguments of the form `linspace(start,stop,number of values)`.

In [ ]:
arr2 = np.linspace(1,5,5)
print(arr2)

[1. 2. 3. 4. 5.]


<div class="alert alert-success">
<b>Task 3.1: Use the linspace function to create a numpy array `data` with the values [10, 20, 30, 40, 50].<br></b>
</div>

In [ ]:
#Enter code for Task 3.1 here
data = np.linspace(10, 50, 5, dtype=np.int16)
print(data)

[10 20 30 40 50]


### 3.1 Mathematical operations on NumPy arrays

A major advantage of NumPy arrays over lists, is that it's straightforward to use mathematical operations.

The mathematical operators used in section 2 work on NumPy arrays in an element-wise fashion. That is, they operate individually on each element. Here are some examples using the array created above.

In [ ]:
# Basic operations
arr_times_two = arr * 2
arr_squared = arr ** 2

print(arr_times_two, arr_squared)

[ 2  4  6  8 10] [ 1  4  9 16 25]


It's also possible to perform maths using two NumPy arrays, but only if they are the same size. For instance, adding one array to another.

In [ ]:
arr_summed = arr_times_two + arr_squared
print(arr_summed)

[ 3  8 15 24 35]


NumPy also includes useful mathematical functions. For example, taking the logarithm or exponential of elements of an array.

In [ ]:
# Useful functions
log_arr = np.log(arr)
exp_arr = np.exp(arr)
print(log_arr,exp_arr)

[0.         0.69314718 1.09861229 1.38629436 1.60943791] [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


As a note that will be particularly useful for the End of Session Task, if you try to take the log of 0 using `np.log` you will get a warning and the resultant element will be infinite.

In [ ]:
np.log(log_arr)

/tmp/ipython-input-4213238566.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(log_arr)


array([       -inf, -0.36651292,  0.09404783,  0.32663426,  0.475885  ])

One way to avoid having zeros in any array is to use the `np.clip()` function. This function will clip any values which are not within the bounds set in the function call. For example, the following code will clip the zero value to 0.01.

In [ ]:
np.clip(log_arr, 0.01, 2.)

array([0.01      , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

<div class="alert alert-success">
<b>Task 3.2: Subtract 10 from the `data` array, clip the array so that no elements are zero and take its logarithm.<br></b>
</div>

In [ ]:
#Enter code for Task 3.2 here
data = np.linspace(10, 50, 5, dtype=np.int16) - 10  # Broadcast.
print(data)
data = np.clip(data, a_min=1e-3, a_max=None)
print(data)
data = np.log(data)
print(data)

[ 0 10 20 30 40]
[1.e-03 1.e+01 2.e+01 3.e+01 4.e+01]
[-6.90775528  2.30258509  2.99573227  3.40119738  3.68887945]


### 3.2 Indexing and slicing

It's often necessary to check the value of one or more elements inside an array, and if the array is particularly long this can be difficult from just visually inspecting the array. Thankfully, NumPy has an easy way to access individual elements of an array, indexing.

A single element of a NumPy array can be indexed using square brackets.

In [ ]:
print("First element:", arr[0])

First element: 1


Remember, in Python indexing starts from 0 (NOT 1!). It's also possible to index from the end of an array by using a minus sign.

In [ ]:
print("Last element:", arr[-1])

print("Third last element:", arr[-3])

Last element: 5
Third last element: 3


Use of square brackets can also be used to access more than one element of an array. This is called slicing. To slice an array, a colon (:) is used. The colon is placed between the elements to slice between, e.g.

In [ ]:
print("First three elements:", arr[0:3])

#Slicing from the first element or to the last element doesn't need the 0 to be included
print("First three elements:", arr[:3])
print("Last three elements:", arr[-3:])

First three elements: [1 2 3]
First three elements: [1 2 3]
Last three elements: [3 4 5]


<div class="alert alert-success">
<b>Task 3.3: Print the first two elements and last element of the logarithm of `data`.<br></b>
</div>

In [ ]:
#Enter code for Task 3.3 here
print(data[:2])
print(data[-1])

[-6.90775528  2.30258509]
3.6888794541139363


## 4. Functions
<a id='functions'></a>

You were previously introduced to functions in first year programming, and we've seen a number of them used in this notebook already! In essence, functions let you reuse code, which can be incredibly useful for carrying out the same actions again and again.

We've already used one function extensively in this notebook, the `print()` function.

In [ ]:
print('Hello')

Hello


Using a function is known as "calling" a function, the above statement calls the `print` function with an argument of 'Hello'. Functions arguments are the inputs to a function and go inside the brackets of a function call.

Now you know how functions are used, but how do you define your own functions? In Python you define them with `def`.

In [ ]:
def square(x):
    return(x ** 2)

The above code is known as a function definition, i.e. where a function is defined. Let's go through this in detail:

- The function definition starts with `def`.
- After `def` comes the name of the function.
- Then, the input to the function (the arguments) are included in brackets immediately after the function name. The arguments can have any name, but this variable name should only be used within the function, it shouldn't be a variable name used outside of the function.
- A colon follows the brackets.
- The contents of the functions (what it does) is included on the lines immediately following the first line. The Python interpreter only includes lines that have been indented after the colon. The next line which is not indented is read as being outside the function.
- Most functions include a return statement. This tells the Python interpreter what the output of the function is. In the case above, the output is the square of the input.

The code above only defines the function `square()`, it doesn't call the function (i.e. use it). Let's try calling the function with a few different arguments.

In [ ]:
square(3)

9

In [ ]:
square(3.4)

11.559999999999999

In [ ]:
square([3,4,5]) #Should get an error

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

The code cell above should throw an error, as it's not possible to square a list!

However, it is possible to square a NumPy array:

In [ ]:
square(arr)

array([ 1,  4,  9, 16, 25])

### 4.1 Multiple arguments

Functions can take multiple arguments and can return multiple objects. If using multiple arguments, these should be separated by a comma.

In [ ]:
def add(a, b):
    return(a + b)

print("Sum of 4 and 5:", add(4, 5))

Sum of 4 and 5: 9


<div class="alert alert-success">
<b>Task 4.1: Write a function to calculate the total number of moles of reactant and product in the reaction $A \rightarrow 2B$, where the arguments should be initial moles of A and the extent of reaction $\chi$. Use the function to calculate the total number of moles at $\chi = 0.4$ when the reaction started with 3 mol of A.<br></b>
<br>
Hint: The number of moles of reactant equals 1 - $\chi$. What are the number of moles of product with respect to $\chi$?
</div>

In [ ]:
#Enter code for Task 4.1 here
def reaction(mol_a: int or float, conversion: float):
  n_a_consumed = (1 - 0.4)  # Consumed reactant: 100% - (reaction percentage),
  n_b = 2 * n_a_consumed  # A -> 2B.
  return n_b

## 5. Lambda functions
<a id='lambda'></a>

Python also allows you to define small functions of a single output using `lambda`.

They are useful for short, throwaway mathematical functions. An example is shown below, where the variable `cube` is assigned a lambda function. The arguments immediately follow the `lambda`, with the output following a colon. Lambda functions should always be single lines of code.

In [ ]:
# A lambda function to compute x^3
cube = lambda x: x**3

cube(2)

8

Lambda functions can take multiple arguments.

In [ ]:
# A lambda function to multiply two variables
multiply = lambda x, y: x * y

multiply(2,3)

6

<div class="alert alert-success">
<b>Task 5.1: Write a lambda function to compute the mole fraction of product in the reaction $A \rightarrow 2B$, where the only required argument is the extent of reaction. Use the function to calculate the mole fraction of B at $\chi = 0.5$.<br></b>
</div>

In [ ]:
#Enter code for Task 5.1 here
b_frac = lambda x: 2 * (1 - x)  # Combine both operations performed in the function.
print(b_frac(0.5))

1.0


## End of Session Task
<a id='final-task'></a>

Write a function called `gibbs_energy` that calculates the Gibbs energy change at different extents of reaction ($\chi$) for a reaction of the form:

<div style="text-align:center">$A(g) \rightarrow 2B(g)$</div><br>

Assume 1 mol of A at $\chi = 0$.

The Gibbs energy change is the sum of contributions from the change in Gibbs energy between reactant and product and the Gibbs energy change due to mixing. The Gibbs energy change due to mixing is given by the equation:

<div style="text-align:center">$\Delta G_{\text{mix}}(\xi) = RT \Big[ n_A\ln(x_A) + n_B\ln(x_B) \Big]$</div>

The function should take as arguments:
- The change in Gibbs energy between the reactant and product.
- The temperature at which the reaction takes place.

The function should return:
- A 1D NumPy array representing the extent of reaction.
- A 1D NumPy array representing the Gibbs energy change for each extent of reaction.

In [ ]:
#Enter code for End of Session Task here
def gibbs_energy(delta_G, T):
  conv_rate = np.linspace(0.00, 1.00, 100)  # 1 pt/%,
  r = 8.314  # Gas constant and temperature,

  """Calculate the total number of mol of A left at each point of the reaction,
  and the amount of B present at each conversion rate point."""
  n_a = np.ones(shape=(100)) - conv_rate  # n_a = (1 - x),
  n_b = 2*conv_rate  # A -> 2B.

  """Calculate total number of mol present in the reaction, and use it to
  compute fractions of A and B in the reaction."""
  n_tot = n_a + n_b
  frac_a, frac_b = n_a / n_tot, n_b / n_tot

  """Compute ΔG, mixing contribution + reaction."""
  dG_mixing = r * T * (n_a*np.log(frac_a) + n_b*np.log(frac_b))
  dG_reaction = delta_G * conv_rate

  dG = np.nan_to_num(dG_mixing, nan=0.0) + dG_reaction  # Avoid NaN!

  return conv_rate, dG


Once you have completed the End of Session Task, run the code cell below to use your code to create an interactive plot of the Gibbs energy of a reaction based on the difference in Gibbs energy of reactant and product!

In [ ]:
from ipywidgets import interact, FloatSlider
import matplotlib.pyplot as plt
import numpy as np

def plot_gibbs(delta_G, T=298):
    xi, dG = gibbs_energy(delta_G, T)

    plt.figure(figsize=(6,4))
    plt.plot(xi, dG, lw=2)
    plt.axhline(0, color='k', ls='--')
    plt.xlabel("Extent of reaction, ξ")
    plt.ylabel("ΔG (J/mol)")
    plt.title(f"Gibbs Energy Profile (ΔG° = {delta_G:.0f} J/mol)")
    plt.grid(True, alpha=0.3)
    plt.show()


# Interactive widget
interact(
    plot_gibbs,
    delta_G=FloatSlider(value=0, min=-2e4, max=2e4, step=1000, description="ΔG° (J/mol)")
);

interactive(children=(FloatSlider(value=0.0, description='ΔG° (J/mol)', max=20000.0, min=-20000.0, step=1000.0…